import Layout from "@/components/layout/Layout"
import Category from "@/components/sections/Category"
import DealProduct1 from "@/components/sections/DealProduct1"
import Product1 from "@/components/sections/Product1"
import Shop from "@/components/sections/Shop"
import Slider1 from "@/components/sections/Slider1"
import { SolrService } from "../src/services/solr-service"
import { Logger } from "sass"

export const metadata = {
    title: 'Ninico - Minimal NextJS React Template',
    description: 'Generated by create next app',
}

export default async function Home() {
    var data = await SolrService.getProductGroups();
    console.log(data);

    return (
        <>
            <Layout headerStyle={1} footerStyle={1}>
                <Slider1 />
                <Category />
                <Product1 />
                <DealProduct1 />
                <Shop />
            </Layout>
        </>
    )
}