// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARfJ4AUIOpGN35XaMpIxhMP9Ttn8MzYJo',
    appId: '1:620954215446:android:fba33dd8e8c44710bb4137',
    messagingSenderId: '620954215446',
    projectId: 'wafi-commerce-8759e',
    storageBucket: 'wafi-commerce-8759e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKYcjjYzZDgFPOYiEvXoYmtaM68VNZpO4',
    appId: '1:620954215446:ios:58b140c64065425dbb4137',
    messagingSenderId: '620954215446',
    projectId: 'wafi-commerce-8759e',
    storageBucket: 'wafi-commerce-8759e.firebasestorage.app',
    iosClientId:
        '620954215446-sqb1tnt6tmfb4bd41maamq2d0t4jqr2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.wafiEcommerce',
  );
}
